---
title: "knhanes svydesign analysis"
output: html_notebook
---
##210317
```{r load dataset}
library(dplyr)

kn <- read.csv("~/proj_ua/data/kn_ua_svy.csv", fileEncoding = "utf-8") %>%
  filter(age>=18 & age<80) %>%
  mutate(
    p = 1,
    level = ifelse(age<65,0,
                   ifelse(age<75,1,2))
  )
glimpse(kn)
```
```{r survey library}
library(survey)
kn_svy <- svydesign(data = kn, id = ~psu+id_fam, strata = ~kstrata, weights = ~wt_12y)
```

```{r survey library subset}
library(survey)
kn_svy_sub <- subset(kn_svy, (!is.na(he_crea) | !is.na(he_uph) | !is.na(he_unitr) | !is.na(he_usg) | !is.na(he_upro) 
                              | !is.na(he_uglu) | !is.na(he_uket) | !is.na(he_ubil) | !is.na(he_ubld) | !is.na(he_uro)))
```

```{r all prevalence sb}
#prevalence <60 , <45
total_sb <- svyby(formula = ~p, by = ~level, design= kn_svy_sub, FUN = svytotal, na.rm = TRUE)

pre60_sb <- svytotal(~eGFR_ab, kn_svy_sub, na.rm=TRUE)[[1]] / (total_sb[1,2] + total_sb[2,2] + total_sb[3,2])*100
pre60_mean_sb <- svymean(~eGFR_ab, kn_svy_sub, na.rm=T)[[1]]*100

pre45_sb <- svytotal(~eGFR_ab45, kn_svy_sub, na.rm=TRUE)[[1]] / (total_sb[1,2] + total_sb[2,2] + total_sb[3,2])*100
pre45_mean_sb <- svymean(~eGFR_ab45, kn_svy_sub, na.rm=T)[[1]]*100

print("sb total all prevalence of 60 =");pre60_sb
print("sb mean all prevalence of 60 =");pre60_mean_sb
print("sb total all prevalence of 45 =");pre45_sb
print("sb mean method all prevalence of 45 =");pre45_mean_sb
```
```{r age 45 model -65, 65-75, 75- prevalence sb}
#prevalence <60 , <45
age_pv_sb <- svyby(formula = ~eGFR_ab + eGFR_ab45, by = ~level, design= kn_svy_sub, FUN = svytotal, na.rm = TRUE)
age_mean_sb <- svyby(formula = ~eGFR_ab + eGFR_ab45, by = ~level, design= kn_svy_sub, FUN = svymean, na.rm = TRUE)

pre60_age0_sb <- age_pv_sb[1,2] / total_sb[1,2] * 100
pre60_age0_mean_sb <- age_mean_sb[1,2] *100
pre60_age1_sb <- age_pv_sb[2,2] / total_sb[2,2] * 100
pre60_age1_mean_sb <- age_mean_sb[2,2] *100
pre60_age2_sb <- age_pv_sb[3,2] / total_sb[3,2] * 100
pre60_age2_mean_sb <- age_mean_sb[3,2] *100

print("sb total age 18-64 prevalence of 60 =");pre60_age0_sb
print("sb mean age 18-64 prevalence of 60 =");pre60_age0_mean_sb
print("sb total age 65-74 prevalence of 60 =");pre60_age1_sb
print("sb mean age 65-74 prevalence of 60 =");pre60_age1_mean_sb
print("sb total age 75- prevalence of 60 =");pre60_age2_sb
print("sb mean age 75- prevalence of 60 =");pre60_age2_mean_sb

pre45_age0_sb <- age_pv_sb[1,3] / total_sb[1,2] * 100
pre45_age0_mean_sb <- age_mean_sb[1,3] *100
pre45_age1_sb <- age_pv_sb[2,3] / total_sb[2,2] * 100
pre45_age1_mean_sb <- age_mean_sb[2,3] *100
pre45_age2_sb <- age_pv_sb[3,3] / total_sb[3,2] * 100
pre45_age2_mean_sb <- age_mean_sb[3,3] *100

print("sb total age 18-64 prevalence of 45 =");pre45_age0_sb
print("sb mean age 18-64 prevalence of 45 =");pre45_age0_mean_sb
print("sb total age 65-74 prevalence of 45 =");pre45_age1_sb
print("sb mean age 65-74 prevalence of 45 =");pre45_age1_mean_sb
print("sb total age 75- prevalence of 45 =");pre45_age2_sb
print("sb mean age 75- prevalence of 45 =");pre45_age2_mean_sb
```

```{r}
n_sb <- c(total_sb[1,2], total_sb[2,2], total_sb[3,2], total_sb[1,2]+total_sb[2,2]+total_sb[3,2])
total_60_sb <- c(pre60_age0_sb, pre60_age1_sb, pre60_age2_sb, pre60_sb)
total_45_sb <- c(pre45_age0_sb, pre45_age1_sb, pre45_age2_sb, pre45_sb)
mean_60_sb <- c(pre60_age0_mean_sb, pre60_age1_mean_sb, pre60_age2_mean_sb, pre60_mean_sb)
mean_45_sb <- c(pre45_age0_mean_sb, pre45_age1_mean_sb, pre45_age2_mean_sb, pre45_mean_sb)

df_pre_sb <- data_frame(n_sb, total_60_sb, mean_60_sb, total_45_sb, mean_45_sb) %>%
  mutate(
    nt60 = n_sb * (total_60_sb/100),
    nm60 = n_sb * (mean_60_sb/100),
    nt45 = n_sb * (total_45_sb/100),
    nm45 = n_sb * (mean_45_sb/100),
  )

df_pre_sb
```