---
title: "knhanes 60model svydesign analysis"
output: html_notebook
author: "chandler"
date: "`r Sys.time()`"
---
##210325
```{r load dataset}
library(dplyr)

kn <- read.csv("~/proj_ua/data/kn_ua_svy.csv", fileEncoding = "utf-8") %>%
  mutate(
    p = 1,
    level = ifelse(age<45,0,
                   ifelse(age<65,1,2))
  )
glimpse(kn)
```
```{r survey library}
library(survey)
kn_svy <- svydesign(data = kn, id = ~psu+id_fam, strata = ~kstrata, weights = ~wt_12y)
```

```{r survey library subset}
library(survey)
kn_svy_sub <- kn_svy %>%
  subset(!is.na(he_crea)) %>%
  subset(!is.na(he_uph)) %>%
  subset(!is.na(he_unitr)) %>%
  subset(!is.na(he_usg)) %>%
  subset(!is.na(he_upro)) %>%
  subset(!is.na(he_uglu)) %>%
  subset(!is.na(he_uket)) %>%
  subset(!is.na(he_ubil)) %>%
  subset(!is.na(he_ubld)) %>%
  subset(!is.na(he_uro)) %>%
  subset(age>=18 & age<80)
```

```{r all prevalence sb}
#prevalence <60 , <45
total_sb <- svyby(formula = ~p, by = ~level, design= kn_svy_sub, FUN = svytotal, na.rm = TRUE)
print(total_sb)

pre60_sb <- svytotal(~eGFR_ab, kn_svy_sub, na.rm=TRUE)[[1]] / (total_sb[1,2] + total_sb[2,2] + total_sb[3,2])*100
pre60_mean_sb <- svymean(~eGFR_ab, kn_svy_sub, na.rm=T)[[1]]*100

print("sb total all prevalence of 60 =");pre60_sb
print("sb mean all prevalence of 60 =");pre60_mean_sb
```
```{r age 60model -50, 50-65, 65- prevalence sb}
#prevalence <60 , <45
age_pv_sb <- svyby(formula = ~eGFR_ab, by = ~level, design= kn_svy_sub, FUN = svytotal, na.rm = TRUE)
age_mean_sb <- svyby(formula = ~eGFR_ab, by = ~level, design= kn_svy_sub, FUN = svymean, na.rm = TRUE)
age_pv_sb
age_mean_sb

pre60_age0_sb <- age_pv_sb[1,2] / total_sb[1,2] * 100
pre60_age0_mean_sb <- age_mean_sb[1,2] *100
pre60_age1_sb <- age_pv_sb[2,2] / total_sb[2,2] * 100
pre60_age1_mean_sb <- age_mean_sb[2,2] *100
pre60_age2_sb <- age_pv_sb[3,2] / total_sb[3,2] * 100
pre60_age2_mean_sb <- age_mean_sb[3,2] *100

print("sb total age0 prevalence of 60 =");pre60_age0_sb
print("sb mean age0 prevalence of 60 =");pre60_age0_mean_sb
print("sb total age1 prevalence of 60 =");pre60_age1_sb
print("sb mean age1 prevalence of 60 =");pre60_age1_mean_sb
print("sb total age2 prevalence of 60 =");pre60_age2_sb
print("sb mean age2 prevalence of 60 =");pre60_age2_mean_sb
```

```{r}
n_sb <- c(total_sb[1,2], total_sb[2,2], total_sb[3,2], total_sb[1,2]+total_sb[2,2]+total_sb[3,2])
total_60_sb <- c(pre60_age0_sb, pre60_age1_sb, pre60_age2_sb, pre60_sb)
mean_60_sb <- c(pre60_age0_mean_sb, pre60_age1_mean_sb, pre60_age2_mean_sb, pre60_mean_sb)

df_pre_sb <- data_frame(n_sb, total_60_sb, mean_60_sb) %>%
  mutate(
    nt60 = n_sb * (total_60_sb/100),
    nm60 = n_sb * (mean_60_sb/100)
  )

df_pre_sb
```


```{r svy design for age, proteinuria}
kn_svy2 <- kn_svy
kn_svy2$variables$he_upro <- ifelse(kn_svy2$variables$he_upro==0,0,1)
table(kn_svy2$variables$he_upro)
```
```{r age proteinuria graph}
shs <- subset(kn_svy2, !is.na(eGFR_ab))
bys <- svyby(~eGFR_ab, ~age+he_upro, svymean, design=shs)
plot(svysmooth(eGFR_ab~age, design=subset(shs,he_upro==0),bandwidth = 1), ylim=c(0,1),ylab = "eGFR<60, prevalence")
lines(svysmooth(eGFR_ab~age, design=subset(shs,he_upro!=0),bandwidth = 1), lwd=2,lty=3)
points(bys$age, bys$eGFR_ab, pch=ifelse(bys$he_upro==0,19,1))
legend("topleft", pch=c(19,1),lty=c(1,3),lwd=c(1,2),legend=c("normal", "proteinuria"),bty="n")
```
