---
title: "study flowchart number"
output: html_notebook
author: "chandler"
time: "`r Sys.time()'"
---

```{r}
library(readxl)
library(dplyr)
raw_cha <- read_excel("proj_ua/data/raw_cha.xlsx",
                      col_types = c("text", "skip", "text", 
                                    "numeric", "skip", "skip", "skip", 
                                    "skip", "text", "skip", "text", "text", 
                                    "text", "text", "text", "text", "text", 
                                    "text", "text", "text", "skip", "skip"))

glimpse(raw_cha)

raw_cha2 <- raw_cha %>%
  filter(나이>=18 & 나이<=90) 
nrow(raw_cha2)

raw_cha3 <- raw_cha2 %>%
  filter(!is.na(LU10101)) %>%
  filter(!is.na(LU10102)) %>%
  filter(!is.na(LU10103)) %>%
  filter(!is.na(LU10104)) %>%
  filter(!is.na(LU10105)) %>%
  filter(!is.na(LU10106)) %>%
  filter(!is.na(LU10107)) %>%
  filter(!is.na(LU10108)) %>%
  filter(!is.na(LU10109)) %>%
  filter(!is.na(LU10110)) 
nrow(raw_cha3)

raw_cha4 <- raw_cha3[!duplicated(raw_cha3$등록번호), ]
nrow(raw_cha4)

for(i in 3:14) {
  print(colnames(raw_cha4[i]))
  print(table(raw_cha4[,i]))
}
```

```{r}
cha_ua <- read.csv("~/proj_ua/data/cha_ua_dataset_v3.csv")

glimpse(cha_ua)

cha_ua2 <- cha_ua %>%
  filter(age>=18 & age<=90) %>%
  unique()
glimpse(cha_ua2)
length(unique(cha_ua2$patient_id))


cha_ua3 <- read.csv("~/proj_ua/data/ua_full_10types_new.v6.csv") %>%
  filter(from=="cha")

glimpse(cha_ua3)

cha_ua4 <- cha_ua3 %>%
  filter(age>=18&age<=90)

glimpse(cha_ua4)
length(unique(cha_ua4$id))

list <- cha_ua4 %>%
  group_by(id) %>%
  summarise(n=n())

cha_ua5 <- cha_ua4[!duplicated(cha_ua4$id), ]


```