---
title: "logistic regression CHA internal validation data, non-proteinuria vs proteinuria // original encoding version"
output: html_notebook
author: "chandler"
date: "`r Sys.time()`"
---


```{r load dataset and clean dataset}
df <- read.csv("~/proj_ua/data/df_lr_cha60_orienco.v1.csv")
glimpse(df)

table(df$ubil)
table(df$uro)

df_glm_non <- df %>%
  filter(upro<2) %>%
  select(-c(eGFR_ckd, id, from, level))

df_glm_pro <- df %>%
  filter(upro>=2) %>%
  select(-c(eGFR_ckd, id, from, level))

glimpse(df_glm_non)
glimpse(df_glm_pro)

table(df_glm_non$ubil)
table(df_glm_pro$ubil)
```

```{r glm non proteinuria}
glm_non <- glm(eGFR_ab ~., family=binomial, data=df_glm_non)
summary(glm_non)

library(gtsummary)
tbl_regression(glm_non, exponentiate = TRUE)
```
```{r glm proteinuria}
glm_pro <- glm(eGFR_ab ~., family=binomial, data=df_glm_pro)
summary(glm_pro)

tbl_regression(glm_pro, exponentiate = TRUE)
```


```{r 45model}
df45 <- read.csv("~/proj_ua/data/df_lr_cha45_orienco.v1.csv") %>%
  mutate(
    eGFR_ab45 = ifelse(eGFR_ckd<45,1,0)
  )
glimpse(df45)
table(df45$uro)
table(df45$ubil)

df45_non <- df45 %>%
  filter(upro<2) %>%
  select(-c(eGFR_ab, eGFR_ckd, id, from, level))
glimpse(df45_non)

df45_pro <- df45 %>%
  filter(upro>=2) %>%
  select(-c(eGFR_ab, eGFR_ckd, id, from, level))
glimpse(df45_pro)
```

```{r 45model glm non-proteinuria}
glm45_non <- glm(eGFR_ab45 ~., family=binomial, data=df45_non)
summary(glm45_non)

tbl_regression(glm45_non, exponentiate = TRUE)
```
```{r 45model glm proteinuria}
glm45_pro <- glm(eGFR_ab45 ~., family=binomial, data=df45_pro)
summary(glm45_pro)

tbl_regression(glm45_pro, exponentiate = TRUE)
```

