---
title: "finding features, different thresholds"
output: html_notebook
autohr: "chandler"
time: "`r Sys.time()`"
---


```{r}
library(dplyr)

df <- read.csv("~/proj_ua/data/df_sub2.csv") %>%
  mutate(
    th56 = prob>0.56,
    th63 = prob>0.63,
    group1 = ifelse(th56==true, 1, 0),
    group2 = ifelse(th63==true, 1, 0)
  )
glimpse(df)
summary(df)
table(df$group2)

df_sub1 = df[df$group1==1,] %>%
  mutate(
    group = 0
  ) %>%
  select(-c(group1, group2))
df_sub2 = df[df$group2==1,] %>%
  mutate(
    group = 1
  ) %>%
  select(-c(group1, group2))

df_rb <- rbind(df_sub1, df_sub2)
table(df_rb$group)


df_lr <- df_rb %>%
  select(-c(prob)) %>%
  select(c(
    group, 
    'male', 
    'he_usg', 
    'he_uph', 
    'he_ubld', 
    'he_uglu', 
    'he_upro', 
    'age'))
summary(df_lr)

df_raw <- read.csv("~/proj_ua/data/df_sub2_raw.csv") %>%
  mutate(
    true = eGFR_ab
    ) %>%
  mutate(
    th56 = prob>0.56,
    th63 = prob>0.63,
    group1 = ifelse(th56==true, 1, 0),
    group2 = ifelse(th63==true, 1, 0)
  )
glimpse(df_raw)

df_raw_sub1 = df_raw[df_raw$group1==1,] %>%
  mutate(
    group = 0
  ) %>%
  select(-c(group1, group2))
df_raw_sub2 = df_raw[df_raw$group2==1,] %>%
  mutate(
    group = 1
  ) %>%
  select(-c(group1, group2))

df_raw_rb <- rbind(df_raw_sub1, df_raw_sub2)
table(df_raw_rb$group)

df_ar <- df_raw_rb %>%
  mutate(
    male = as.character(male),
    he_upro_c = as.character(he_upro)
  )

```

```{r, logistic regression }
glm <- glm(group ~., family=binomial, data=df_lr)
summary(glm)

library(gtsummary)
tbl_regression(glm, exponentiate = TRUE)
```


```{r, arsenal}
library(arsenal)
library(knitr)

stat_tbl1 <- tableby(group ~ male + age + he_usg + he_uph + he_ubld + he_upro + he_uglu, data=df_ar, total=FALSE)
summary(stat_tbl1, text=TRUE)
kable(summary(stat_tbl1))
```

```{r, kwt}
stat_tbl2 <- tableby(group ~ he_upro + he_uglu + he_ubld, data=df_ar, total=F, numeric.stats=c("medianrange","q1q3"), numeric.test="kwt")
summary(stat_tbl2, test=T)
```

