---
title: "severance dataset"
output: html_notebook
author: "chandler"
time: "`r Sys.time()`"
---

```{r}
library(dplyr)

df_ys <- read.csv("~/proj_ua/data/df_ys_new.csv")
glimpse(df_ys)

df <- df_ys %>%
  select(
    c(
      patient_id,
      male,
      age,
      blood,
      ph,
      sg,
      protein,
      glucose,
      eGFR_ckd
      )
  ) %>%
  rename(
    "he_ubld" = blood,
    "he_uph" = ph,
    "he_usg" = sg,
    "he_upro" = protein,
    "he_uglu" = glucose
  ) %>%
  mutate(
    eGFR_ab = ifelse(eGFR_ckd<60,1,0)
  ) %>%
  unique()

write.csv(df, "~/proj_ua/data/df_ys_new_v2.csv", fileEncoding = "utf-8", row.names = F)
```

```{r, ua, raw dataset}
ua <- read_excel("~/dataset/data_yonsei/ys_ua_raw.xlsx")
glimpse(ua)

ua_sel <- ua[,c(3,4,6,9,14,16,18,22,24,26,27,29,34,36)] 
colnames(ua_sel) <- c("p_id","sex","age","cr","he_unitr","he_uro","he_upro","he_ubil","he_uket","he_ubld","he_uph","he_usg","leuko","he_uglu")
glimpse(ua_sel)

ua_sel2 <- ua_sel %>%
  mutate(
    male = ifelse(sex=="M",1,0),
    age = as.numeric(age),
    cr = as.numeric(cr),
    he_uph = as.numeric(he_uph),
    he_usg = as.numeric(he_usg),
    eGFR_ckd = ifelse(
      male == 1, 
      ifelse(cr <= 0.9, 141*((cr/0.9)^-0.411)*0.993^age, 141*((cr/0.9)^-1.209)*0.993^age), 
      ifelse(cr <=0.7, 144*((cr/0.7)^-0.329)*0.993^age, 144*((cr/0.7)^-1.209)*0.993^age)
                      ),
    eGFR_ab = ifelse(eGFR_ckd<60,1,0)
  ) %>%
  select(-c(sex, cr)) %>%
  filter(
    !is.na(he_upro),
    !is.na(he_ubld),
    !is.na(he_uglu),
    !is.na(he_uph),
    !is.na(he_usg),
    !is.na(eGFR_ckd),
    age>=18,
    he_usg<1.5
    ) %>%
  unique()
glimpse(ua_sel2)

table(ua_sel2$he_upro, exclude=F)
table(ua_sel2$he_uglu, exclude=F)
table(ua_sel2$he_ubld, exclude=F)
table(ua_sel2$he_uph, exclude=F)
table(ua_sel2$he_usg, exclude=F)

ua_sel3 <- ua_sel2 %>%
  mutate(
    ##
    he_uglu = ifelse(he_uglu=="Negative" | he_uglu=="-",0,
                     ifelse(he_uglu=="Trace" | he_uglu=="+/-",1,
                            ifelse(he_uglu=="1+",2,
                                   ifelse(he_uglu=="2+",3,
                                          ifelse(he_uglu=="3+",4,5))))),
    ##
    he_unitr = ifelse(he_unitr=="Negative" | he_unitr=="-",0,1),
    ##
    he_upro = ifelse(he_upro=="Negative" | he_upro=="-",0,
                     ifelse(he_upro=="Trace" | he_upro=="+/-",1,
                            ifelse(he_upro=="1+",2,
                                   ifelse(he_upro=="2+",3,
                                          ifelse(he_upro=="3+",4,5))))),
    ##
    he_ubil = ifelse(he_ubil=="Negative" | he_ubil=="-",0,
                     ifelse(he_ubil=="Trace" | he_ubil=="+/-",1,
                            ifelse(he_ubil=="1+",2,
                                   ifelse(he_ubil=="2+",3,
                                          ifelse(he_ubil=="3+",4,5))))),
    ##
    he_uket = ifelse(he_uket=="Negative" | he_uket=="-",0,
                     ifelse(he_uket=="Trace" | he_uket=="+/-",1,
                            ifelse(he_uket=="1+",2,
                                   ifelse(he_uket=="2+",3,
                                          ifelse(he_uket=="3+",4,5))))),
    ##
    he_ubld = ifelse(he_ubld=="Negative" | he_ubld=="-",0,
                     ifelse(he_ubld=="Trace" | he_ubld=="TRACE" | he_ubld=="+/-",1,
                            ifelse(he_ubld=="1+",2,
                                   ifelse(he_ubld=="2+",3,
                                          ifelse(he_ubld=="3+",4,5))))),
    ##
    he_uph = as.numeric(ifelse(he_uph==">=9.0",9.0, he_uph)),
    ##
    he_usg = as.numeric(gsub("[[:punct:]]","", he_usg)),
    he_usg = ifelse(he_usg<=1007, 1.005, 
                    ifelse(he_usg>=1008 & he_usg<=1012, 1.010,
                           ifelse(he_usg>=1013 & he_usg<=1017, 1.015,
                                  ifelse(he_usg>=1018 & he_usg<=1022, 1.020,
                                         ifelse(he_usg>=1023 & he_usg<=1027, 1.025, 1.030))))),
    ##
    leuko = ifelse(leuko=="Negative" | leuko=="-",0,
                     ifelse(leuko=="Trace" | leuko=="+/-",1,
                            ifelse(leuko=="1+",2,
                                   ifelse(leuko=="2+",3,
                                          ifelse(leuko=="3+",4,5))))),
    ##
    he_uro = ifelse(he_uro=="-",0,
                     ifelse(he_uro=="+/-(0.1)" | he_uro=="+/-(0.2)",1,
                            ifelse(he_uro=="1+(1.0)" | he_uro=="1+(16)",2,
                                   ifelse(he_uro=="2+(2.0)" | he_uro=="2+(4.0)" | he_uro=="2+(66)",3,
                                          ifelse(he_uro=="3+(4.0)" | he_uro=="3+(8.0)",4,5)))))
  ) %>%
  unique()
glimpse(ua_sel3)

write.csv(ua_sel3, "~/proj_ua/data/df_ys_ua_new_v2111.csv", fileEncoding = "utf-8", row.names = F)
```

